### PR TITLE
feat(plugin): add support for build 242.x compatibility

### PR DESCRIPTION
**Pull request by Cleboost**
I just updated the view package and the authorized version. After a quick test everything works. I'll let you check

### CODE REVIEW

**Review by marceloavf — APPROVED** [review]

**Comment by victororlyk** [comment]
can someone please approve this workflow?) really strugling without this plugin

**Review by thomasbnt — APPROVED** [review]

**Comment by Cleboost** [comment]
> can someone please approve this workflow?) really strugling without this plugin

I have 2 approves reviews on the branch but we have to wait for the repo owner... It takes a long time 😢

**Comment by victororlyk** [comment]
@Cleboost maybe you need to assign him, so he will see it in his notifications?)
@nekofar  please review

**Comment by Cleboost** [comment]
I don't think I can change the assignment

**Comment by ezBeanie** [comment]
*bump*

**Comment by geekscloud** [comment]
Can you merge it quickly? I need the plugin to be compatible with the new version.

**Comment by Cleboost** [comment]
I'm building it. You can install it manually with the .zip file. Only, it won't have the official plugin signature.

**Comment by geekscloud** [comment]
> I'm building it. You can install it manually with the .zip file. Only, it won't have the official plugin signature.

I will refer to your modification and compile a version compatible with 24.2.1 by myself.
∠( ᐛ 」∠)＿

**Comment by Cleboost** [comment]
I saw that there was a new EAP but that the “view” dependency was not yet up to date. So I can't without updating the dependency. We'll have to wait
image

**Comment by geekscloud** [comment]
> I saw that there was a new EAP but that the “view” dependency was not yet up to date. So I can't without updating the dependency. We'll have to wait我看到有一个新的 EAP，但 "视图 "依赖关系尚未更新。因此，我不能不更新依赖关系。我们必须等待 image
242.22855.33 is too high a version. After testing, 242.21829.165 is compatible with 24.2.1

**Comment by geekscloud** [comment]
> I saw that there was a new EAP but that the “view” dependency was not yet up to date. So I can't without updating the dependency. We'll have to wait我看到有一个新的 EAP，但 "视图 "依赖关系尚未更新。因此，我不能不更新依赖关系。我们必须等待 image

242.22855.33 is too high a version. After testing, 242.21829.165 is compatible with 24.2.1

**Review by nekofar — COMMENTED** [review]
@dependabot recreate

**Pull request closed without merging**
